import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";
import { ThemeProvider } from "next-themes";
import { ModeToggle } from "@/components/theme-toggle";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
       <head>
        <script
          dangerouslySetInnerHTML={{
            __html: `
              (function() {
                try {
                  var theme = localStorage.getItem('theme') || 'dark';
                  var html = document.documentElement;
                  // Remove any previous theme classes
                  var themes = ${JSON.stringify([
                    "light",
                    "dark",
                    "cupcake",
                    "bumblebee",
                    "emerald",
                    "corporate",
                    "synthwave",
                    "retro",
                    "cyberpunk",
                    "valentine",
                    "halloween",
                    "garden",
                    "forest",
                    "aqua",
                    "lofi",
                    "pastel",
                    "fantasy",
                    "wireframe",
                    "black",
                    "luxury",
                    "dracula",
                  ])};
                  html.classList.remove('dark');
                  themes.forEach(t => html.classList.remove('theme-' + t));

                  if(theme === 'dark') {
                    html.classList.add('dark');
                  } else {
                    html.classList.add('theme-' + theme);
                  }
                } catch(e) {}
              })();
            `,
          }}
        />
      </head>
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider 
             attribute="class"
            defaultTheme="system"
            enableSystem
            disableTransitionOnChange>

        <header className="fixed top-0 z-50 w-full shadow-md" 
          >
        <div className="flex items-center gap-6 px-10 py-3 mx-auto text-white">
          
          {/* Logo */}
          <a className="flex flex-col items-center border-r border-white pr-6">
            <svg
              xmlns="http://www.w3.org/2000/svg"
              fill="none"
              viewBox="0 0 24 24"
              strokeWidth="1.5"
              stroke="currentColor"
              className="w-7 h-7"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                d="M15.75 10.5V6a3.75 3.75 0 1 0-7.5 0v4.5m11.356-1.993 1.263 12c.07.665-.45 1.243-1.119 1.243H4.25a1.125 1.125 0 0 1-1.12-1.243l1.264-12A1.125 1.125 0 0 1 5.513 7.5h12.974c.576 0 1.059.435 1.119 1.007Z"
              />
            </svg>

            <h3 className="text-xl font-semibold uppercase">Bondify</h3>
          </a> 

          {/* Nav */}
         <nav className="flex gap-6 uppercase text-sm">
            <Link href="/">Home</Link>
            <Link href="/products">Product</Link>
            <Link href="">Category</Link>
            
            <div>
                 <ModeToggle/>
            </div>

          </nav>
        </div>
       
      </header>

     <main className="pt-24">{children}</main>
          
        </ThemeProvider>
      </body>
    </html>
  );
}
